User can delete selected QR codes.
Kiptong/QReator pull request #8
Opened 2017-07-19 22:12 UTC by Kiptong

2017-07-19 22:36 UTC, victormejia requested changes

2017-07-19 22:36 UTC, victormejia commented on index.js
> +      .then(() => res.json(qrCode))
you should return here in the response the object that knex gives you. To do so, chain a `.returning('*')` after the `.into()`

2017-07-19 22:36 UTC, victormejia commented on index.js
> +    .then((data) => res.json(data))
does the query actually give you back any data?

2017-07-19 22:36 UTC, victormejia commented on index.js
> +app.delete('/deleteqr/:id', (req, res) => {
this should be the same path `qrcodes/:id`

2017-07-19 22:41 UTC, Kiptong commented on index.js
> +    .then((data) => res.json(data))
Honestly I'm really not sure if that even needs to be there.

2017-07-20 16:37 UTC, victormejia commented on index.js
> +      .then((data) => console.log(res.json(data)))
you are not responding back here...

2017-07-20 16:38 UTC, victormejia requested changes

2017-07-20 16:38 UTC, victormejia commented on index.js
> +    .then((data) => res.json(data))
then you should probably just reply with a 200 status code: `res.sendStatus(200)`

2017-07-20 17:19 UTC, victormejia approved these changes

2017-07-20 17:55 UTC, merged